fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TESTENV:
    database: SNOWFLAKE_LEARNING_DB
    schema: TEST_ENV
  WORK:
    database: PC_COALESCE_DB
    schema: PUBLIC
name: Production
type: Environment
