fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: SNOWFLAKE_LEARNING_DB
    schema: PROD_ENV
name: Production
type: Environment
